version: "3.9"

name: contacts_stack

services:
  db:
    image: postgres:16-alpine
    container_name: contacts_db
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: contacts_web
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - web_static:/app/static
    networks:
      - backend

  nginx:
    image: nginx:1.27-alpine
    container_name: contacts_nginx
    depends_on:
      - web
    ports:
      - "${PUBLIC_HTTP_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - web_static:/app/static:ro
    networks:
      - backend

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: contacts_jenkins
    user: root
    environment:
      JENKINS_OPTS: "--httpPort=${JENKINS_PORT}"
    ports:
      - "${JENKINS_PORT}:${JENKINS_PORT}"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Jenkinsfile:/var/jenkins_home/workspace-template/Jenkinsfile:ro
    networks:
      - backend

volumes:
  pgdata:
  web_static:
  jenkins_home:

networks:
  backend:
    driver: bridge
