name: contacts_stack

services:
  db:
    image: postgres:16-alpine
    container_name: contacts_db
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: contacts_web
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - web_static:/app/static
    networks:
      - backend
    expose:
      - "8000"   # internal-only; nginx talks to this

  nginx:
    build:
      context: ./nginx
    image: contacts-nginx:local
    container_name: contacts_nginx
    depends_on:
      - web
    ports:
      - "${PUBLIC_HTTP_PORT}:80"  # e.g. 8210:80
    volumes:
      - web_static:/app/static:ro
    networks:
      - backend

volumes:
  pgdata:
  web_static:

networks:
  backend:
    driver: bridge
